### ISSUE TITLE
Compilation error on rustc 1.80.0

### ISSUE THREAD

**Issue by nafkhanzam** [tingerrr/typst-project#1]
Got this error when trying to install UTPM using cargo install + rustc 1.80.0, which uses this project. I don't know rust, but I hope this image is self-explanatory.

![image](https://github.com/user-attachments/assets/54e92d20-247b-4957-b76f-6de9deb6077f)

**Comment by tingerrr** [comment]
Did you install `utpm` using the `--locked` flag? If not, try that, this seems like a breaking change on the side of the `email_address` crate. Indeed, it had a breaking change between 0.2.5 to 0.2.6, I'll pin it to stay below 0.2.5.

EDIT:

upstream issue is here: https://github.com/johnstonskj/rust-email_address/issues/29
